language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: T0J0VYADSg9NX9op2lKRBPqyYMb7rLNXRpTU90LOFgk6+kFNlwQePbiA2F2wnVLndi8Ix2Kga2GCDs8MfWQBRy4dqzbbeJ9DNmXOYWMazFbTmG33xZIJoAO+X8iyGf5qElHHcLTN51+AzcZvTYZTYoy0adQKKwQZjCrImXtWprQ=
  app: hubot-tfrkd-slack
  on:
    repo: furu/hubot-tfrkd-slack
notifications:
  slack:
    secure: b/albFMBBJP8Wc+RKQOP/3lUn2TCw6FjnZgFasdd4ObdzhZlgMqmN+nDaeEQOit6B9NMk4COPvl+8RBY1876ZEd/p++LyXvmnNHK8Cd+TZwfHbr88knfYhDFm0LzrUKZiYjZg/e0OlwxEnpPpaNjszaFMMS/Jwpx9bkMn1k/3iM=
